import enum

class Role(str, enum.Enum):
    USER = "USER"
    STAFF = "STAFF"
    ADMIN = "ADMIN"

class ComplaintStatus(str, enum.Enum):
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
    REJECTED = "REJECTED"

class Priority(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class Category(str, enum.Enum):
    WATER = "WATER"
    ELECTRICITY = "ELECTRICITY"
    ROADS = "ROADS"
    SANITATION = "SANITATION"
    TRANSPORT = "TRANSPORT"
    SAFETY = "SAFETY"
    OTHER = "OTHER"

class NotificationType(str, enum.Enum):
    COMPLAINT_CREATED = "COMPLAINT_CREATED"
    COMPLAINT_ASSIGNED = "COMPLAINT_ASSIGNED"
    STATUS_UPDATED = "STATUS_UPDATED"
    COMMENT_ADDED = "COMMENT_ADDED"
    COMPLAINT_RESOLVED = "COMPLAINT_RESOLVED"
    COMPLAINT_CLOSED = "COMPLAINT_CLOSED"
    COMPLAINT_ESCALATED = "COMPLAINT_ESCALATED"
    COMPLAINT_REJECTED = "COMPLAINT_REJECTED"
    COMPLAINT_REOPENED = "COMPLAINT_REOPENED"
    COMPLAINT_PRIORITY_CHANGED = "COMPLAINT_PRIORITY_CHANGED"
    FEEDBACK_REQUEST = "FEEDBACK_REQUEST"
    ADMIN_ANNOUNCEMENT = "ADMIN_ANNOUNCEMENT"
    SYSTEM_NOTIFICATION = "SYSTEM_NOTIFICATION"
    SLA_WARNING = "SLA_WARNING"
    SLA_BREACHED = "SLA_BREACHED"

class NotificationChannel(str, enum.Enum):
    IN_APP = "IN_APP"
    EMAIL = "EMAIL"

class NotificationPriority(str, enum.Enum):
    NORMAL = "NORMAL"
    IMPORTANT = "IMPORTANT"
    CRITICAL = "CRITICAL"

class EscalationLevel(str, enum.Enum):
    LEVEL_1 = "LEVEL_1"
    LEVEL_2 = "LEVEL_2"
    LEVEL_3 = "LEVEL_3"
